### PR TITLE
Mod dependency support

### PR DESCRIPTION
**Pull request by almafa64**
ModLoader collects all mod by id now, after that recursivly loads all dependencies first and lastly the mod.

### CODE REVIEW

**Comment by WackyModer** [comment]
Can you kinda document it?

How would I use this in a mod for example

Also how does it tell the name if it only uses id's?

**Comment by almafa64** [comment]
Where should i document it?

It uses the ids for checking quickly what mods exists
Ids are the key for each ModInfo in a dictionary before loading completed
so you can get the modname from id or looping through the dict

## usage
Lets say I have 2 mods: A and B.
I write mod A which uses a library B.
Than i write in the modinfo.yaml for A:
```yaml
entrypoint: 
    dll: TestMainMod.dll
    className: TestMainMod.Plugin
attributes:
    id: com.almafa64.ModA
    name: Mod A
    description: the A mod for Bopl
    version: "1.0"
    authors: 
        - almafa64
    dependencies:
        - com.someoneelse.LibraryB
```
and if com.someoneelse.LibarayB doesnt exists then mod A won't be loaded and a warning given.

**Comment by WackyModer** [comment]
Looks good!

I'll ask Codemob before merging rq

**Comment by codemob-dev** [comment]
I was planning on doing this already, I'll go ahead and merge!

**Pull request merged**
